version: '2'
services:
        engineering:
                build: .
                image: engineering
                container_name: linux_embedded_dev
                environment:
                        - GOPATH=/root/Projects/sensity/code/golang
                volumes:
                        - $HOME/Projects:/root/Projects
                tty: true
        # cloud:
        #         image: sensitydockerrepo/api-base:1.0
        #         container_name: cloud_dev
        #         volumes:
        #                 - $HOME/Projects:/root/Projects
        #         tty: true
